### ISSUE TITLE
Initial condition of a capacitor

### ISSUE THREAD

**Issue by OndrejBukovsky** [MatyasVasek/SymCirc#5]
**Describe the bug**
```
Current version of Symcirc: 0.1.1
Traceback (most recent call last):
  File "C:\projects\geec\python\tranError.py", line 20, in <module>
    circuit = AnalyseCircuit(netlist, "tran", symbolic=True, method="tableau")
  File "C:\Users\z004ehkv\AppData\Local\Programs\Python\Python310\lib\site-packages\symcirc\analysis.py", line 65, in __init__
    self.eqn_matrix, self.solved_dict, self.symbols = self._analyse()  # solved_dict: {sympy.symbols(<vaviable_name>): <value>}
  File "C:\Users\z004ehkv\AppData\Local\Programs\Python\Python310\lib\site-packages\symcirc\analysis.py", line 377, in _analyse
    eqn_matrix, symbols = self._build_system_eqn()
  File "C:\Users\z004ehkv\AppData\Local\Programs\Python\Python310\lib\site-packages\symcirc\analysis.py", line 508, in _build_system_eqn
    self._add_basic(M, R, c, index)
  File "C:\Users\z004ehkv\AppData\Local\Programs\Python\Python310\lib\site-packages\symcirc\analysis.py", line 1062, in _add_basic
    vi_vector[self.c_count + index, 0] += val*c.init_cond
TypeError: unsupported operand type(s) for *: 'Symbol' and 'NoneType'
```

**To Reproduce**
```python
# Resistor divider with capacitor
import sys
import json

from symcirc import *

from importlib.metadata import version
sys.stderr.write(f"Current version of Symcirc: {version('symcirc')}\n")

netlist = """

V1 1 0 DC 1 AC 1 0 SIN 0 1 1k 0 0
R1 1 2 1k
R2 2 0 1k
C1 2 0 500n
"""
# C1 2 0 500n IC=0 works

circuit = AnalyseCircuit(netlist, "tran", symbolic=True, method="tableau")
results = circuit.node_voltages()
results.update(circuit.component_values("all"))

print(json.dumps(results))

```

**Comment by MatyasVasek** [comment]
Fixed the issue for both capacitors and inductors
